targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: true
          include_if_null: false